[package]
name = "fii-id"
version = "0.1.0"
authors = ["Woomy4680-exe <matzar1808@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"